VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "IObject_Class"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
' T‰m‰ On Abstrakti Luokka Joka Ei Toteuta Mit‰‰n
Public Active As Boolean
Public Visible As Boolean

Public Sub Load(CEngine As ScriptControl)
    
End Sub

Public Sub Update(CEngine As ScriptControl)

End Sub
